### ISSUE TITLE
Python errors when nondbshow searchs can't be found

### ISSUE THREAD

**Issue by poo706** [8cylinder/tv-overlord#32]
When running `tvol nondbshow --ignore "search term"` (both BT and Usenet) and searching for a search term that doesn't exist, you get the following:

```
No results found.                                                                                                             
Traceback (most recent call last):
  File "/usr/bin/tvol", line 11, in <module>
    sys.exit(tvol())
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/tvoverlord/tvol.py", line 375, in nondbshow
    nons.non_db(search_string, count)
  File "/usr/lib/python3.5/site-packages/tvoverlord/show.py", line 336, in non_db
    self._download(show_data)
  File "/usr/lib/python3.5/site-packages/tvoverlord/show.py", line 437, in _download
    search_type=Config.search_type)
  File "/usr/lib/python3.5/site-packages/tvoverlord/search.py", line 277, in download
    chosen_show, destination, final_name)
  File "/usr/lib/python3.5/site-packages/tvoverlord/search_providers/nzbclub_com.py", line 134, in download
    urllib.request.urlretrieve(href, fullname)
  File "/usr/lib/python3.5/urllib/request.py", line 188, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 451, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/usr/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/usr/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'skip'
```

**Comment by 8cylinder** [comment]
Fixed in dev branch: 7fd3791afbf3f6d2ea1cbf2ed267d7a4a39dbdc1

**Comment by poo706** [comment]
How should tvol be updated as you make these commits?

**Comment by 8cylinder** [comment]
Once I push an update to pypi then you can `pip3 install --update tvoverlord`.  This will also update any dependencies as well.  I will also make a note on the tvoverlord.com website about the new version number and any changes.  

I don't have a schedule I follow for pypi releases, but It is nice to have a handful of changes in one release.

Also, you can use git to clone the project and run it that way, any changes I make will be available to you right away.  Theoretically that's more unstable because that code hasn't been tested as much.  To use it this way, I recommend installing it in a virtualenv.  A 1000 foot overview of that is:

1. Install and activate virtualenv (pip may or may not have already installed it)
1. `git clone https://github.com/8cylinder/tv-overlord.git`
1. `git checkout dev` (use the dev branch, thats the bleeding edge)
1. `python3 setup.py bdist_wheel`
1. `pip3 install --editable .`

Now whenever you run `git pull` tvol will be updated to the most recent changes.

A good overview of virtualenv is here: http://docs.python-guide.org/en/latest/dev/virtualenvs/

**Comment by poo706** [comment]
The pip3 upgrade worked perfect to take me to 1.4.1, thanks. And I can confirm that your recent commits fixed the issues, nice work!
