### ISSUE TITLE
nondbshow does not work

### ISSUE THREAD

**Issue by alex-calderwood** [8cylinder/tv-overlord#33]
I've tried it a few times on various movies.

Error Message:

```
$ tvol nondbshow "annie hall"

  annie hall


  annie hall
 |Name                                       |      Size|Date        | Seeds|SE
a|Annie Hall (1977) 720▒V x264 - 600MB - YIFY|  601.3 MB|Sep 05/2011 |   178|BT
b|Woody Allen - Annie H▒uRay - BRRIP x264 mkv|   1.35▒GB|11-27▒2011  |    44|PB
Traceback (most recent call last):
  File "c:\users\pie_a\anaconda3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\pie_a\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\pie_a\Anaconda3\Scripts\tvol.exe\__main__.py", line 9, in <module>
  File "c:\users\pie_a\anaconda3\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\pie_a\anaconda3\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\users\pie_a\anaconda3\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\pie_a\anaconda3\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\pie_a\anaconda3\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\users\pie_a\anaconda3\lib\site-packages\tvoverlord\tvol.py", line 347, in nondbshow
    nons.non_db(search_string, count)
  File "c:\users\pie_a\anaconda3\lib\site-packages\tvoverlord\show.py", line 254, in non_db
    None, None, display_count)
  File "c:\users\pie_a\anaconda3\lib\site-packages\tvoverlord\show.py", line 344, in _ask
    show_to_dl = tbl.generate()
  File "c:\users\pie_a\anaconda3\lib\site-packages\tvoverlord\consoletable.py", line 167, in generate
    click.echo(bar.join(row_arr))
  File "c:\users\pie_a\anaconda3\lib\site-packages\click\utils.py", line 259, in echo
    file.write(message)
  File "c:\users\pie_a\anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2-5: character maps to <undefin
```

**Comment by 8cylinder** [comment]
I think you're using windows. Try running `chcp 65001` before you run tvol.  This sets the console to unicode.  On my windows test machine, `chcp` returns 437, you could try that also.

What version of Windows are you using?

A possible workaround is to use a different terminal.  I recomend [conemu](http://conemu.github.io/), it has pretty good unicode support.

There is a discussion of this issue at superuser.com: http://superuser.com/questions/269818/change-default-code-page-of-windows-console-to-utf-8.

**Comment by alex-calderwood** [comment]
Okay I'll try it, thanks!

**Comment by 8cylinder** [comment]
If you still have the problem, reopen this issue.
