### ISSUE TITLE
Copy error

### ISSUE THREAD

**Issue by 8cylinder** [8cylinder/tv-overlord#35]
When running `tvol copy` and source doesn't exist... bad things happen.

```
Traceback (most recent call last):
  File "/home/sm/.local/bin/tvol", line 9, in <module>
    load_entry_point('tvoverlord', 'console_scripts', 'tvol')()
  File "/home/sm/.local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/sm/.local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/sm/.local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sm/.local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sm/.local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/sm/projects/media-downloader/tvoverlord/tvoverlord/tvol.py", line 466, in copy
    hist.copy()
  File "/home/sm/projects/media-downloader/tvoverlord/tvoverlord/history.py", line 119, in copy
    DownloadManager(torrent_hash, torrent_dir, torrent_name)
  File "/home/sm/projects/media-downloader/tvoverlord/tvoverlord/downloadmanager.py", line 88, in __init__
    source = self.get_show_file(filename)
  File "/home/sm/projects/media-downloader/tvoverlord/tvoverlord/downloadmanager.py", line 274, in get_show_file
    size = os.stat(full_filename).st_size
OSError: [Errno 36] File name too long: '\x1b[30m\x1b[9m~/shows/Halt.and.Catch.Fire.S03E03.720p.HDTV.x264-AVS[PRiME]\x1b[0m/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/.DS_Store'
```

\x1b[30m\x1b[9m~/shows/Halt.and.Catch.Fire.S03E03.720p.HDTV.x264-AVS[PRiME]\x1b[0m/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/Supernatural/.DS_Store'

**Comment by 8cylinder** [comment]
fixed: dbf0f022eb42c1460f64ece0ea5e8a4f667d5335
