### ISSUE TITLE
Rare and random python errors

### ISSUE THREAD

**Issue by poo706** [8cylinder/tv-overlord#48]
I did a manual usenet search, found what I wanted, pressed "a" to make my selection, and immediately got the following:

```
Letter or [q]uit: a
Traceback (most recent call last):
  File "/usr/bin/tvol", line 11, in <module>
    sys.exit(tvol())
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/tvoverlord/tvol.py", line 447, in nondbshow
    nons.non_db(search_string, count)
  File "/usr/lib/python3.5/site-packages/tvoverlord/show.py", line 307, in non_db
    self._download(show_data)
  File "/usr/lib/python3.5/site-packages/tvoverlord/show.py", line 425, in _download
    search_type=Config.search_type)
  File "/usr/lib/python3.5/site-packages/tvoverlord/search.py", line 291, in download
    chosen_show, destination, final_name)
  File "/usr/lib/python3.5/site-packages/tvoverlord/search_providers/nzbclub_com.py", line 133, in download
    urllib.request.urlretrieve(href, fullname)
  File "/usr/lib/python3.5/urllib/request.py", line 188, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```

I went through the exact same steps and it worked fine a second time.  This has happened on one other occasion.

**Comment by 8cylinder** [comment]
It looks like the download was timing out.  I'll catch that error and give a more informative error message.

**Comment by 8cylinder** [comment]
tvol will say "Download timed out, try again." when it times out now.
