### ISSUE TITLE
Unusual python error after tvol list

### ISSUE THREAD

**Issue by poo706** [8cylinder/tv-overlord#49]
I've never seen this one before, it has output this each time after 3 attempts to run tvol list.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 535, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 298, in _error_catcher
    yield
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 590, in read_chunked
    self._update_chunk_length()
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 539, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 694, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 428, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 618, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 316, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tvol", line 11, in <module>
    sys.exit(tvol())
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/tvoverlord/tvol.py", line 358, in list_missing
    for series in bar:
  File "/usr/lib/python3.5/site-packages/click/_termui_impl.py", line 257, in next
    return next(self.iter)
  File "/usr/lib/python3.5/site-packages/tvoverlord/shows.py", line 55, in __next__
    show = Show(dbdata=self.dbdata[self.i])
  File "/usr/lib/python3.5/site-packages/tvoverlord/show.py", line 62, in __init__
    self._get_thetvdb_series_data()
  File "/usr/lib/python3.5/site-packages/tvoverlord/show.py", line 121, in _get_thetvdb_series_data
    series = tv[self.db_name]
  File "/usr/lib/python3.5/site-packages/tvdb_api.py", line 952, in __getitem__
    sid = self._nameToSid(key)
  File "/usr/lib/python3.5/site-packages/tvdb_api.py", line 937, in _nameToSid
    self._getShowData(selected_series['id'], selected_series['language'])
  File "/usr/lib/python3.5/site-packages/tvdb_api.py", line 884, in _getShowData
    epsEt = self._getetsrc( url, language=language)
  File "/usr/lib/python3.5/site-packages/tvdb_api.py", line 621, in _getetsrc
    src = self._loadUrl(url, language=language)
  File "/usr/lib/python3.5/site-packages/tvdb_api.py", line 559, in _loadUrl
    resp = self.session.get(url)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests_cache/core.py", line 126, in request
    **kwargs
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.5/site-packages/requests_cache/core.py", line 99, in send
    return send_request_and_cache_response()
  File "/usr/lib/python3.5/site-packages/requests_cache/core.py", line 91, in send_request_and_cache_response
    response = super(CachedSession, self).send(request, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 641, in send
    r.content
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 772, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 697, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

**Comment by 8cylinder** [comment]
I just started getting that error today also.  It looks like thetvdb is having issues with their api.  I'll put some exception handling in to give a more informative error message.

This error might go away after a couple of days.  I've had similar things happen before with thetvdb.
