### ISSUE TITLE
ExtraTorrent search error

### ISSUE THREAD

**Issue by LiquidLemon** [8cylinder/tv-overlord#51]
This happens when I try to download anything.
```
Traceback (most recent call last)
  File "/usr/local/bin/tvol", line 11, in <module>
    sys.exit(tvol())
  File "/home/liquidlemon/.local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/liquidlemon/.local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/liquidlemon/.local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/liquidlemon/.local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/liquidlemon/.local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tvoverlord/tvol.py", line 424, in download
    show.download_missing(count, today)
  File "/usr/local/lib/python3.5/dist-packages/tvoverlord/show.py", line 172, in download_missing
    search_type=Config.search_type,
  File "/usr/local/lib/python3.5/dist-packages/tvoverlord/search.py", line 150, in search
    results = future.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tvoverlord/search.py", line 56, in job
    search_results = search.search(search_string, season, episode)
  File "/usr/local/lib/python3.5/dist-packages/tvoverlord/search_providers/extratorrent.py", line 69, in search
    size = U.pretty_filesize (show['size'])
  File "/home/liquidlemon/.local/lib/python3.5/site-packages/feedparser.py", line 357, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'size'
```
I fixed the problem for myself by wrapping the problematic code in a try-except statement but that's a rather hacky solution.

**Comment by 8cylinder** [comment]
It looks like extratorrents rss feed is malformed.  I've got a fix in the works but it might be a day before I can get it out .  In the meantime add extratorrent to the blacklist in the config file.  

`blacklist: ExtraTorrent`

More details on adding search engines to the blacklist:
https://github.com/8cylinder/tv-overlord/wiki/Config-file

**Comment by LiquidLemon** [comment]
Thank you very much, my fault for not having read the docs.

**Comment by 8cylinder** [comment]
No problem!  I need to re-think how tvol handles errors from the various search engines.  My policy was to wait for errors to happen and then add exceptions, since there are so many possible things that could go wrong.  

But that's no good for other people using the program.  They end up with a program that doesn't function until I can get an update out.

**Comment by 8cylinder** [comment]
I've uploaded the new version with a fix.
