### ISSUE TITLE
tvdb api v1 support ends October 1st, 2017

### ISSUE THREAD

**Issue by CeruleanSky** [8cylinder/tv-overlord#67]
[tvdb api v1 support ends October 1st, 2017](https://forums.thetvdb.com/viewtopic.php?f=3&t=36557).   

Possible Solutions:  

* Use [tvdbsimple that has v2 support](https://github.com/phate89/tvdbsimple)  instead of tvdb_api
* [Use this fork of tvdb_api](https://github.com/dpimenov/tvdb_api/tree/newapi) that supports v2 if it is stable enough
* Wait and see if the [tvdb_api package being currently used gets an update](https://github.com/dbr/tvdb_api/tree/master)

A benefit to the new api is supposedly it is less prone to server errors and truncations due to how it is hosted and better maintained.

**Comment by janschulz** [comment]
I had a look at the second project (fork of tvdb_api to v2 and it's not finished yet: there are still a few places where xml is expected and tvol triggers this places :-(

example of `tvol calendar`:
```py
  File "/home/js/external/tv-overlord/tvoverlord/show.py", line 153, in _get_thetvdb_series_data
    series = self.tvapi[self.db_name]
  File "/home/js/external/tvdb_api/tvdb_api.py", line 835, in __getitem__
    sid = self._nameToSid(key)
  File "/home/js/external/tvdb_api/tvdb_api.py", line 821, in _nameToSid
    self._getShowData(selected_series['id'], self.config['language'])
  File "/home/js/external/tvdb_api/tvdb_api.py", line 790, in _getShowData
    "%r is %r" % (child.tag, child.text) for child in cur_ep.getchildren()))
AttributeError: 'dict' object has no attribute 'getchildren'
```

**Comment by janschulz** [comment]
You might try this: https://github.com/janschulz/tvdb_api/tree/v1_compat

I added a compatibility layer so that he v1 keys work again on the v2 API. It's enough to make 'tvol calendar' and 'tvol download' work again.

**Comment by CeruleanSky** [comment]
Thanks @janschulz , I upgraded to your fork and branch and everything seems to work.

For those who want to try it out until there is an upstream solution run the below:  

```py -3 -m pip install -U git+git://github.com/janschulz/tvdb_api.git@v1_compat```

**Comment by janschulz** [comment]
The changes are now submitted upstream: https://github.com/dbr/tvdb_api/pull/58

**Comment by kwinczek** [comment]
Hey,

after running `pip3 install -U git+git://github.com/janschulz/tvdb_api.git@v1_compat` I get:

```
● tvol list
 ****                                               Better Call Saul
Traceback (most recent call last):
  File "/usr/local/bin/tvol", line 11, in <module>
    sys.exit(tvol())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tvoverlord/tvol.py", line 389, in list_missing
    fp.standard_print(series.show_missing())
  File "/usr/local/lib/python3.6/site-packages/tvoverlord/show.py", line 301, in show_missing
    ret += ' - %s, %s' % (self.airs_dayofweek, self.airs_time)
AttributeError: 'Show' object has no attribute 'airs_dayofweek'
```

and:

```
● tvol add narcos
Multiple shows found, type a number to select.
Type "<ctrl> c" to cancel.

Traceback (most recent call last):
  File "/usr/local/bin/tvol", line 11, in <module>
    sys.exit(tvol())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tvoverlord/tvol.py", line 461, in add
    new_show.add_new(name=show_name)
  File "/usr/local/lib/python3.6/site-packages/tvoverlord/show.py", line 333, in add_new
    title = show['seriesname']
KeyError: 'seriesname'
```

**Comment by janschulz** [comment]
Seems that I missed a few backwards incompatible changes :-/

**Comment by janschulz** [comment]
I added the missing (or just some: "works for me") pieces to https://github.com/8cylinder/tv-overlord/pull/69

**Comment by janschulz** [comment]
It seems the v2 changes were added to tvapi, not sure if they re already released...

**Comment by CeruleanSky** [comment]
Thanks for the update.  As the fixes you collaborated on are being merged to the mainline version of tvapi which tv-overlord depends on, 

> [If people can test out the latest master (06bb4cfd050b395d1bdec755211b0808addf3099), I can make a new release of this soon](https://github.com/dbr/tvdb_api/pull/58#issuecomment-320423422)

and of which a release is just awaiting some feedback, I'm closing this ticket.
