### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by JPFrancoia** [8cylinder/tv-overlord#72]
Hi, I'm getting a ```JSONDecodeError``` when trying to ```tvol download "Westworld"```:

```
Traceback (most recent call last):                                                                                      
  File "/usr/bin/tvol", line 11, in <module>   RARBG   The Pirate Bay 
    sys.exit(tvol())
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/tvoverlord/tvol.py", line 438, in download
    show.download_missing(count, today)
  File "/usr/lib/python3.6/site-packages/tvoverlord/show.py", line 228, in download_missing
    search_type=Config.search_type,
  File "/usr/lib/python3.6/site-packages/tvoverlord/search.py", line 168, in search
    results = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/tvoverlord/search.py", line 71, in job
    search_results = search.search(search_string, season, episode)
  File "/usr/lib/python3.6/site-packages/tvoverlord/search_providers/rarbg_to.py", line 70, in search
    results = r.json()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I'm on Archlinux, ```tvoverlord``` installed from Pypi, version 1.5.0.

Any idea where the issue comes from ?

Best

**Comment by jankatins** [comment]
Might be resolved by #73
