### ISSUE TITLE
Async became a reserved keyword in python 3.7, thus SyntaxError is raised: async = True

### ISSUE THREAD

**Issue by kbaikov** [8cylinder/tv-overlord#74]
See: 
https://docs.python.org/3.7/reference/compound_stmts.html#async
and 
https://docs.python.org/3.7/whatsnew/3.7.html

Steps to reproduce:
  1. Install python 3.7
  2. run tvol (download|calendar)

Actual result: Exception is raised:
Traceback (most recent call last):
  File "c:\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\python3\scripts\tvol.exe\__main__.py", line 5, in <module>
  File "c:\python3\lib\site-packages\tvoverlord\tvol.py", line 14, in <module>
    from tvoverlord.shows import Shows
  File "c:\python3\lib\site-packages\tvoverlord\shows.py", line 4, in <module>
    from tvoverlord.show import Show
  File "c:\python3\lib\site-packages\tvoverlord\show.py", line 13, in <module>
    from tvoverlord.search import Search, SearchError
  File "c:\python3\lib\site-packages\tvoverlord\search.py", line 15, in <module>
    from tvoverlord.search_providers import *
  File "c:\python3\lib\site-packages\tvoverlord\search_providers\__init__.py", line 21, in <module>
    from . import eztv_ag
  File "c:\python3\lib\site-packages\tvoverlord\search_providers\eztv_ag.py", line 67
    async = True

Expected result: tvol runs successfully

Platform: win 10, Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32

**Comment by JPFrancoia** [comment]
Yes, same issue here. Thanks for the fix.

I see there are several PR opened for a while. Is this project still active?
